fevercatdream/mesoamerican-museum

controllers/homeRoutes.js
controllers/index.js
server.js

-Basic server setup to be able to setup routes. 
-import and export home routes into the controller index file
-basic homeRoute for testing to make sure get route is working

creating server js file, controller index file, placeholder homeroutes 

---

controllers/api/index.js
controllers/api/museumRoutes.js
server.js

added GET and POST routes for museum
added GET and POST routes for logging into museum

Id museum routes

---

controllers/homeRoutes.js

Adding placeholder routes to handlebar pages

adding basic routes for handlebar pages

---

controllers/api/artTypeRoutes.js
controllers/api/artWorkRoutes.js
controllers/api/civRoutes.js
controllers/api/index.js

adding routes for artType and Civ
adding additional routes for artWorks
updating artWork routes to include foreign keys
adding routing to index files

Id art work routes

---

controllers/homeRoutes.js

adding catalogoptions route in homeRoutes

Home routes

---

server.js
utils/cloudinary.js

cloudinary set up on the server

cloudinary.js, imported to server.js

---

public/js/additem.js

add a new artwork

---

controllers/api/index.js
controllers/api/museumRoutes.js
controllers/api/userRoutes.js
models/museum.js
models/user.js

-adding routes for creating/updating/getting users
-updating models to include bcrypt on museum and user passwords

Id user routes

---

public/js/catalogoptions.js
public/js/deleteitem.js

delete an arwork

---

public/js/index.js
public/js/login.js
views/index.handlebars

updated login and logout scripts

Id loginlogout

---

public/js/catalogoptions.js

connection to login, logout, add,  delete, and update by button

catalogoptions.js

---

controllers/homeRoutes.js
public/js/index.js
views/catalog.handlebars
views/partials/carosel.handlebars

adding partials for catalog handlebars

Id handlebar testing

---

public/js/catalog.js
public/js/catalogoptions.js
public/js/index.js
public/js/login.js
public/js/singleart.js
views/catalog.handlebars
views/catalogoptions.handlebars
views/singleart.handlebars

-adding links from museum icon to home on catalog page and singleart page
-updating links from catalogoptions to respective pages

Id index2catalog link

---

models/employee.js
models/index.js
models/visitor.js
public/js/login.js

modified index.js, now employee.js, visitor.js

renaming tables in models

---

controllers/homeRoutes.js
public/js/catalog.js
views/catalog.handlebars
views/index.handlebars
views/partials/carosel.handlebars
views/partials/footer.handlebars
views/singleart.handlebars

-Updating singleArt handlebars
-Updating catalog.js script to window direct to specific art page

pulling data from db to show on single art screen

---

package.json
public/js/catalog.js
seeds/seed.js
views/catalog.handlebars

Fixing splide bug
Includes seeds script

Id fixing splide bug 

---

controllers/api/visitorRoutes.js
public/js/icon.js
public/js/usercollection.js

likes and user collection

---

controllers/api/artWorkRoutes.js
public/js/updateitem.js
views/updateitem.handlebars

-Adding frontend scripts to update item
-Adding backend routes to update item in database

adding update CRUD operation to catalogoptions

---

controllers/homeRoutes.js
public/js/additem.js
public/js/catalogoptions.js
public/js/deleteitem.js
public/js/updateitem.js
views/additem.handlebars
views/deleteitem.handlebars
views/index.handlebars
views/updateitem.handlebars

adding home and logout button for additem and updateitem

adding button functionality to add and update

---

controllers/api/artWorkRoutes.js
controllers/homeRoutes.js
public/js/deleteitem.js
views/deleteitem.handlebars

adding CRUD functionality to delete item page

adding delete CRUD functionality

---

public/js/additem.js
public/js/deleteitem.js
views/partials/catalogType.handlebars

adding redirection to catalog on successful delete

adding redirection to delete page

---

public/js/additem.js
views/additem.handlebars

Id frontend cloudinary

---

public/js/updateitem.js
views/updateitem.handlebars

adding cloudinary upload widget to update item page

Id cloudinaryupddate

---

controllers/homeRoutes.js
public/js/login.js

adding redirects when not logged in

Id user logins

---

controllers/homeRoutes.js
public/js/additem.js
public/js/deleteitem.js
public/js/updateitem.js
views/additem.handlebars
views/deleteitem.handlebars
views/updateitem.handlebars

adding success messages after crud operations
adding some error handling on delete if no item is found with given id

adding success messages after CRUD operations
